bills/urls.py
from django.conf.urls import url
from . import views

app_name = 'bills'
urlpatterns = [
    url(r'^$',views.accounts, name='accounts'),
    url(r'login/', views.login, name='login'),
    url(r'^create_account/$', views.createAccount, name="create_account"),
    url(r'^accounts/(?P<account_id>[0-9]+)/bills/$', views.accountBills, name="account_bills"),
]

learning/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'', include('bills.urls'), name='bills'),
    url(r'^admin/', admin.site.urls),
]

bills/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


# Create your models here.

@python_2_unicode_compatible
class Account(models.Model):
    account_name = models.CharField(max_length=80)
    created_date = models.DateTimeField('date created')

    def __str__(self):
        return self.account_name

@python_2_unicode_compatible
class Bill(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    bill_name = models.CharField(max_length=80)
    bill_amount = models.IntegerField()
    bill_date =  models.DateField()

    def __str__(self):
        return self.bill_name

bills/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Account, Bill

def login(request):
    # import pdb; pdb.set_trace()
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('bills:accounts'))
    else:
        return render(request,'login.html')

@login_required
def accounts(request):
    accounts =  Account.objects.all()
    template_values = {
        'accounts' : accounts
    }
    return render(request, 'accounts.html', template_values)

@login_required
def createAccount(request):
    if request.method == 'POST':
        new_account = request.POST.get("new_account")
        create_account = Account(account_name = new_account, created_date= timezone.now())
        create_account.save()
        return HttpResponseRedirect(reverse('bills:accounts'))
    else:
        return HttpResponseRedirect(reverse('bills:account_bills'))

@login_required
def accountBills(request, account_id):
    if request.method == 'POST':
        account = Account.objects.get(pk=account_id)
        name = request.POST.get('bill_name')
        amount = request.POST.get('bill_amount')
        date =  request.POST.get('bill_date')
        account.bill_set.create(bill_name=name, bill_amount=amount, bill_date=date)
        return HttpResponseRedirect(reverse('bills:account_bills', kwargs={'account_id':account_id}))

    else:
        account = Account.objects.get(pk=account_id)
        account_bills = account.bill_set.all()
        template_values = {
            'account': account,
            'account_bills':account_bills
        }
        return render(request, 'account_bills.html', template_values)

bills/templates/account_bills.html
{% extends "base.html" %}
{% block title %}{{ account.account_name }} Bills{% endblock %}

{% block content %}
    <div class="container">
        <h4>Account: {{ account.account_name }}</h2>
      <div class="card row section">
        <div class="col s8 offset-s2">
          <h5 class="center-align">Add a Bill</h5>
          <form action="{% url 'bills:account_bills' account.id %}" method="post">
            {% csrf_token %}
            <div class="input-field col s12">
                <input id="bill_name" type="text" name="bill_name">
                <label for="bill_name" class="active">Bill Title</label>
            </div>
            <div class="input-field col s12">
                <input id="bill_amount" type="text" name="bill_amount">
                <label for="bill_amount" class="active">Bill Amount</label>
            </div>
            <div class="input-field col s12">
                <input id="bill_date" type="date" name="bill_date">
                <label for="bill_date" class="active">Bill Date</label>
            </div>
            <div class="col s6">
                <button class="btn waves-effect waves-light" type="submit" name="action">Add</button>
            </div>
          </form>
        </div>

      </div>
      <table class="stripped">
        <thead>
          <tr>
              <th data-field="id">Bill Name</th>
              <th data-field="name">Bill Amount</th>
              <th data-field="price">Bill Date</th>
          </tr>
        </thead>
        <tbody>
          {% for bill in account_bills %}
          <tr>
            <td>{{ bill.bill_name }}</td>
            <td>{{ bill.bill_amount }}</td>
            <td>{{ bill.bill_date }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

bills/templates/accounts.html
{% extends "base.html" %}
{% block title %}Accounts{% endblock %}

{% block content %}
  <div class="container row">
      <div class="col s12">
          <ul class="collection with-header">
              <li class="collection-header">
                  <h4>Your Accounts</h4></li>
              {% for account in accounts %}
              <li class="collection-item"><a href="{% url 'bills:account_bills' account.id %}">{{ account.account_name }}</a></li>
              {% endfor %}
          </ul>
      </div>

      <div>
          <form action="{% url 'bills:create_account' %}" method="post">
              {% csrf_token %}
              <div class="input-field col s6">
                  <input id="account_name" type="text" name="new_account">
                  <label for="account_name">Create an Account</label>
                  <button class="btn waves-effect waves-light" type="submit">Create</button>
              </div>
          </form>
      </div>
  </div>
{% endblock %}

bills/templates/base.html
{% load static %}
<html>

<head>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}"> {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% block content %}{% endblock %}
</body>

</html>

bills/templates/login.html
{% extends "base.html" %} {% block head %}
<script src="https://apis.google.com/js/platform.js" async defer></script>
<meta name="google-signin-client_id" content="679302979041-c74i7bs32a3tdk1sf8ggpvs7psbd2kkp.apps.googleusercontent.com"> {% endblock %} {% block title %}Login{% endblock%} {% block content %}
<div class="container center-align welcome-content">

    <h3>Welcome to Bills.</h3>
    <a class="waves-effect waves-light btn" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with your Google email</a>
</div>

{% endblock %}